CREATE TABLE IF NOT EXISTS archived_files (
    id            TEXT PRIMARY KEY,   -- uuid, generated by us
    shoot_id      TEXT NOT NULL,      -- FK to Ridwan's shoots table, joined loosely for now
    path          TEXT NOT NULL,      -- original path/filename
    original_size INTEGER NOT NULL,
    hash          TEXT NOT NULL,      -- content hash, key into the object store
    stored_size   INTEGER NOT NULL,
    codec         TEXT NOT NULL,
    codec_version INTEGER NOT NULL,
    codec_params  TEXT,               -- JSON-encoded map[string]string
    codec_blob    BLOB,               -- recipe.Blob
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_archived_files_shoot ON archived_files(shoot_id);
